# General settings
project_path: "/home/VLAI/thinhpn/CNN_RNN_VQA/"
output_path: "/home/VLAI/thinhpn/CNN_RNN_VQA/outputs/"

# Training parameters
train:
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  batch_size: 16
  learning_rate: 0.0001
  epochs: 1

# Logging
save_model: true
model_save_path: "models/vqa_counting.pt"

# Dataset
dataset: 
  name: "VQAv2"
  path: "/home/VLAI/datasets/VQAv2/"
  image_path: "/home/VLAI/datasets/COCO_Images/train2014/"
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  max_samples: 1000
  
